name: Smoke test

on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    permissions:
      contents: read # to fetch code (actions/checkout)
      issues: write # to create comment
      pull-requests: read # for searching pull requests

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          # This is set to the lowest Node.js version we support
          node-version: 20
          cache: 'yarn'
      - run: |
          yarn install
          yarn build
          ln -s ../ node_modules/eslint-plugin-jest
      - uses: AriPerkkio/eslint-remote-tester-run-action@5724813c126b48e735e7fc08f048f318c3df262d # v5
        with:
          issue-title: 'Results of weekly scheduled smoke test'
          eslint-remote-tester-config: eslint-remote-tester.config.ts
